# verison: '3'
services: 
    web: 
        build: 
        command: python3 /code/manage.py runserver 0.0.0.0.8000
        volumes: 
          - .:/code
        ports: 
           - 8000:8000
        depond_on:
          - db 
        env_file:
          -.env 
    db: 
        image: mysql 
        restart: always
        command: --default-authentication-plugin-mysql_native_password --mysqlx=0
        enviroment:
            MYSQL_DATABASE: demo
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - ".dbdata:/var/lib/mysql"
        ports:
            - '3305:3306'
        env_file:
            - .env
        